In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split

def ConvertDateintoDay_Month_Year(df):
    #newdf = pd.DataFrame()
    df.Date = pd.to_datetime(df.Date)
    #df["Nav"] = df.Nav
    df["day"] = df.Date.dt.day
    df["month"] = df.Date.dt.month
    df["year"] = df.Date.dt.year
    df["day_of_week"] = df.Date.dt.dayofweek
    df = df.drop(columns=["Unnamed: 0","Date"],axis=1)
    return df

In [2]:
directory =  os.path.join(os.getcwd())
file = r"SBI Contra fund featured data.csv"
df = pd.read_csv(os.path.join(directory,file))
df = ConvertDateintoDay_Month_Year(df)
print(df)

            Open  avg_month_return  risk_free_rate  excess_return  \
0     117.468002         -0.120525            0.21      -0.210000
1     118.628998         -0.120525            0.21      -0.210000
2     119.311996         -0.120525            0.21       0.778351
3     119.295998         -0.120525            0.21       0.365743
4     119.210999         -0.120525            0.21      -0.223409
...          ...               ...             ...            ...
1226  242.364807          0.533991            0.21      -0.405647
1227  241.635498          0.533991            0.21       0.641454
1228  244.246399          0.533991            0.21      -0.510914
1229  245.949799          0.533991            0.21       0.870512
1230  246.789703          0.533991            0.21       0.487410

      previous_close  previous_day_return  day  month  year  day_of_week
0           0.000000             0.000000    9      3  2018            4
1         117.468002             0.000000   12      3  2018            0
2         118.628998             0.988351   13      3  2018            1
3         119.311996             0.575743   14      3  2018            2
4         119.295998            -0.013409   15      3  2018            3
...              ...                  ...  ...    ...   ...          ...
1226      240.318604            -0.195647    1      3  2023            2
1227      242.364807             0.851454    2      3  2023            3
1228      241.635498            -0.300914    3      3  2023            4
1229      244.246399             1.080512    6      3  2023            0
1230      245.949799             0.697410    8      3  2023            2

[1231 rows x 10 columns]

In [21]:
newdf = pd.get_dummies(df, columns=['day_of_week', 'month'])

In [23]:
newdf

,Open,avg_month_return,risk_free_rate,excess_return,previous_close,previous_day_return,day,year,day_of_week_0,day_of_week_1,...,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12
0,117.468002,-0.120525,0.21,-0.210000,0.000000,0.000000,9,2018,0,0,...,1,0,0,0,0,0,0,0,0,0
1,118.628998,-0.120525,0.21,-0.210000,117.468002,0.000000,12,2018,1,0,...,1,0,0,0,0,0,0,0,0,0
2,119.311996,-0.120525,0.21,0.778351,118.628998,0.988351,13,2018,0,1,...,1,0,0,0,0,0,0,0,0,0
3,119.295998,-0.120525,0.21,0.365743,119.311996,0.575743,14,2018,0,0,...,1,0,0,0,0,0,0,0,0,0
4,119.210999,-0.120525,0.21,-0.223409,119.295998,-0.013409,15,2018,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,242.364807,0.533991,0.21,-0.405647,240.318604,-0.195647,1,2023,0,0,...,1,0,0,0,0,0,0,0,0,0
1227,241.635498,0.533991,0.21,0.641454,242.364807,0.851454,2,2023,0,0,...,1,0,0,0,0,0,0,0,0,0
1228,244.246399,0.533991,0.21,-0.510914,241.635498,-0.300914,3,2023,0,0,...,1,0,0,0,0,0,0,0,0,0
1229,245.949799,0.533991,0.21,0.870512,244.246399,1.080512,6,2023,1,0,...,1,0,0,0,0,0,0,0,0,0
1230,246.789703,0.533991,0.21,0.487410,245.949799,0.697410,8,2023,0,0,...,1,0,0,0,0,0,0,0,0,0

In [24]:
mm = preprocessing.MinMaxScaler()

In [25]:
col_names = list(newdf.columns)
scaled_df = mm.fit_transform(newdf)
scaled_df = pd.DataFrame(scaled_df,columns = col_names)
scaled_df

,Open,avg_month_return,risk_free_rate,excess_return,previous_close,previous_day_return,day,year,day_of_week_0,day_of_week_1,...,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12
0,0.252360,0.562714,0.0,0.642390,0.000000,0.642390,0.266667,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.258830,0.562714,0.0,0.642390,0.466824,0.642390,0.366667,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.262636,0.562714,0.0,0.699081,0.471438,0.699081,0.400000,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.262546,0.562714,0.0,0.675414,0.474152,0.675414,0.433333,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.262073,0.562714,0.0,0.641621,0.474088,0.641621,0.466667,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,0.948356,0.904915,0.0,0.631168,0.955038,0.631168,0.000000,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1227,0.944292,0.904915,0.0,0.691229,0.963170,0.691229,0.033333,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1228,0.958841,0.904915,0.0,0.625130,0.960272,0.625130,0.066667,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1229,0.968333,0.904915,0.0,0.704368,0.970648,0.704368,0.166667,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1230,0.973014,0.904915,0.0,0.682393,0.977417,0.682393,0.233333,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
y = scaled_df["Open"]
X = scaled_df.drop(columns=["Open","risk_free_rate"],axis=1)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [32]:
def train_model(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)
    
    regr = LinearRegression()
    regr.fit(X_train, y_train)
    regr_y_pred = regr.predict(X_test)
    mae = mean_absolute_error(y_test, regr_y_pred)
    print("Linear regression:")
    print('MAE:', mae)
    print("Model Score : ",regr.score(X_test, y_test))
    print("------------------------------------")
    
    rnd = RandomForestRegressor()
    rnd.fit(X_train, y_train)
    rnd_y_pred = rnd.predict(X_test)
    mae = mean_absolute_error(y_test, rnd_y_pred)
    print("Random Forest Regression")
    print('MAE:', mae)
    print("Model Score: ",rnd.score(X_test, y_test))
    print("-------------------------------------")
    
    model = Pipeline([('scaler', StandardScaler()), ('svr', SVR())])
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    print("Support Vector Regressor")
    print('MAE:', mae)
    print("Model Score: ",model.score(X_test, y_test))

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

train_model(X,y)

Linear regression:
MAE: 0.006910822456701202
Model Score :  0.9988857670606877
------------------------------------
Random Forest Regression
MAE: 0.006626624378943708
Model Score:  0.9989390660312112
-------------------------------------
Support Vector Regressor
MAE: 0.0701888782002374
Model Score:  0.9214051053572809